export const FORECAST_REQUEST = "FORECAST_REQUEST";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_FAILED = "FORECAST_FAILED";

export const CHANGE_ACTIVE_INDEX = "CHANGE_ACTIVE_INDEX";